<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pais;
use Illuminate\Support\Facades\DB;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['nombre'=>'Afganistán', 'codigo_movil'=>'93'],
            ['nombre'=>'Albania', 'codigo_movil'=>'355'],
            ['nombre'=>'Argelia', 'codigo_movil'=>'213'],
            ['nombre'=>'Samoa Americana', 'codigo_movil'=>'1 (684)'],
            ['nombre'=>'Andorra', 'codigo_movil'=>'376'],
            ['nombre'=>'Angola', 'codigo_movil'=>'244'],
            ['nombre'=>'Anguila', 'codigo_movil'=>'1 (264)'],
            ['nombre'=>'Antigua y Barbuda', 'codigo_movil'=>'1 (268)'],
            ['nombre'=>'Argentina', 'codigo_movil'=>'54'],
            ['nombre'=>'Armenia', 'codigo_movil'=>'374'],
            ['nombre'=>'Aruba', 'codigo_movil'=>'297'],
            ['nombre'=>'Australia', 'codigo_movil'=>'61'],
            ['nombre'=>'Territorio australiano', 'codigo_movil'=>'672'],
            ['nombre'=>'Austria', 'codigo_movil'=>'43'],
            ['nombre'=>'Azerbaiyán', 'codigo_movil'=>'994'],
            ['nombre'=>'Bahamas', 'codigo_movil'=>'1 (242)'],
            ['nombre'=>'Bahrain', 'codigo_movil'=>'973'],
            ['nombre'=>'Bangladesh', 'codigo_movil'=>'880'],
            ['nombre'=>'Barbados', 'codigo_movil'=>'1 (246)'],
            ['nombre'=>'Belarus', 'codigo_movil'=>'375'],
            ['nombre'=>'Bélgica', 'codigo_movil'=>'32'],
            ['nombre'=>'Belice', 'codigo_movil'=>'501'],
            ['nombre'=>'Benín', 'codigo_movil'=>'229'],
            ['nombre'=>'Bermuda', 'codigo_movil'=>'1 (441)'],
            ['nombre'=>'Bután', 'codigo_movil'=>'975'],
            ['nombre'=>'Bolivia', 'codigo_movil'=>'591'],
            ['nombre'=>'Bosnia/Herzegovina', 'codigo_movil'=>'387'],
            ['nombre'=>'Botsuana', 'codigo_movil'=>'267'],
            ['nombre'=>'Brasil', 'codigo_movil'=>'55'],
            ['nombre'=>'Islas Vírgenes Británicas', 'codigo_movil'=>'1 (284)'],
            ['nombre'=>'Brunéi', 'codigo_movil'=>'673'],
            ['nombre'=>'Bulgaria', 'codigo_movil'=>'359'],
            ['nombre'=>'Burkina Faso', 'codigo_movil'=>'226'],
            ['nombre'=>'Burundi', 'codigo_movil'=>'257'],
            ['nombre'=>'Camboya', 'codigo_movil'=>'855'],
            ['nombre'=>'Camerún', 'codigo_movil'=>'237'],
            ['nombre'=>'Islas de Cabo Verde', 'codigo_movil'=>'238'],
            ['nombre'=>'Islas Caimán', 'codigo_movil'=>'1 (345)'],
            ['nombre'=>'República Centroafricana', 'codigo_movil'=>'236'],
            ['nombre'=>'Chad', 'codigo_movil'=>'235'],
            ['nombre'=>'Chile', 'codigo_movil'=>'56'],
            ['nombre'=>'China', 'codigo_movil'=>'86'],
            ['nombre'=>'Colombia', 'codigo_movil'=>'57'],
            ['nombre'=>'Comoras', 'codigo_movil'=>'269'],
            ['nombre'=>'Congo (DROC), República Democrática del', 'codigo_movil'=>'243'],
            ['nombre'=>'Congo (ROC), República de', 'codigo_movil'=>'242'],
            ['nombre'=>'Islas Cook', 'codigo_movil'=>'682'],
            ['nombre'=>'Costa Rica', 'codigo_movil'=>'506'],
            ['nombre'=>'Croacia', 'codigo_movil'=>'385'],
            ['nombre'=>'Cuba', 'codigo_movil'=>'53'],
            ['nombre'=>'Chipre', 'codigo_movil'=>'357'],
            ['nombre'=>'República Checa', 'codigo_movil'=>'420'],
            ['nombre'=>'Dinamarca', 'codigo_movil'=>'45'],
            ['nombre'=>'Diego García', 'codigo_movil'=>'246'],
            ['nombre'=>'Yibuti', 'codigo_movil'=>'253'],
            ['nombre'=>'Dominica', 'codigo_movil'=>'1 (767)'],
            ['nombre'=>'República Dominicana', 'codigo_movil'=>'1 (809/829/849)'],
            ['nombre'=>'Ecuador', 'codigo_movil'=>'593'],
            ['nombre'=>'Egipto', 'codigo_movil'=>'20'],
            ['nombre'=>'El Salvador', 'codigo_movil'=>'503'],
            ['nombre'=>'Guinea Ecuatorial', 'codigo_movil'=>'240'],
            ['nombre'=>'Eritrea', 'codigo_movil'=>'291'],
            ['nombre'=>'Estonia', 'codigo_movil'=>'372'],
            ['nombre'=>'Etiopía', 'codigo_movil'=>'251'],
            ['nombre'=>'Islas Malvinas', 'codigo_movil'=>'500'],
            ['nombre'=>'Islas Feroe', 'codigo_movil'=>'298'],
            ['nombre'=>'Fiyi', 'codigo_movil'=>'679'],
            ['nombre'=>'Finlandia', 'codigo_movil'=>'358'],
            ['nombre'=>'Francia', 'codigo_movil'=>'33'],
            ['nombre'=>'Guyana Francesa', 'codigo_movil'=>'594'],
            ['nombre'=>'Gabón', 'codigo_movil'=>'241'],
            ['nombre'=>'Gambia', 'codigo_movil'=>'220'],
            ['nombre'=>'Georgia', 'codigo_movil'=>'995'],
            ['nombre'=>'Alemania', 'codigo_movil'=>'49'],
            ['nombre'=>'Ghana', 'codigo_movil'=>'233'],
            ['nombre'=>'Gibraltar', 'codigo_movil'=>'350'],
            ['nombre'=>'Grecia', 'codigo_movil'=>'30'],
            ['nombre'=>'Groenlandia', 'codigo_movil'=>'299'],
            ['nombre'=>'Granada', 'codigo_movil'=>'1 (473)'],
            ['nombre'=>'Guadalupe (Antillas Francesas)', 'codigo_movil'=>'590'],
            ['nombre'=>'Guatemala', 'codigo_movil'=>'502'],
            ['nombre'=>'Guernsey', 'codigo_movil'=>'44'],
            ['nombre'=>'Guinea', 'codigo_movil'=>'224'],
            ['nombre'=>'Guinea-Bisáu', 'codigo_movil'=>'245'],
            ['nombre'=>'Guyana', 'codigo_movil'=>'592'],
            ['nombre'=>'Haití', 'codigo_movil'=>'509'],
            ['nombre'=>'Honduras', 'codigo_movil'=>'504'],
            ['nombre'=>'Hong Kong', 'codigo_movil'=>'852'],
            ['nombre'=>'Hungría', 'codigo_movil'=>'36'],
            ['nombre'=>'Islandia', 'codigo_movil'=>'354'],
            ['nombre'=>'India', 'codigo_movil'=>'91'],
            ['nombre'=>'Indonesia', 'codigo_movil'=>'62'],
            ['nombre'=>'Irán', 'codigo_movil'=>'98'],
            ['nombre'=>'Iraq', 'codigo_movil'=>'964'],
            ['nombre'=>'Irlanda', 'codigo_movil'=>'353'],
            ['nombre'=>'Isla de Man', 'codigo_movil'=>'44'],
            ['nombre'=>'Israel', 'codigo_movil'=>'972'],
            ['nombre'=>'Italia', 'codigo_movil'=>'39'],
            ['nombre'=>'Costa de Marfil', 'codigo_movil'=>'225'],
            ['nombre'=>'Jamaica', 'codigo_movil'=>'1 (876)'],
            ['nombre'=>'Japón', 'codigo_movil'=>'81'],
            ['nombre'=>'Jersey', 'codigo_movil'=>'44'],
            ['nombre'=>'Jordania', 'codigo_movil'=>'962'],
            ['nombre'=>'Kazajistán', 'codigo_movil'=>'7'],
            ['nombre'=>'Kenia', 'codigo_movil'=>'254'],
            ['nombre'=>'Kiribati', 'codigo_movil'=>'686'],
            ['nombre'=>'Corea (Norte)', 'codigo_movil'=>'850'],
            ['nombre'=>'Corea (Sur)', 'codigo_movil'=>'82'],
            ['nombre'=>'Kuwait', 'codigo_movil'=>'965'],
            ['nombre'=>'Kirguizistán', 'codigo_movil'=>'996'],
            ['nombre'=>'Laos', 'codigo_movil'=>'856'],
            ['nombre'=>'Letonia', 'codigo_movil'=>'371'],
            ['nombre'=>'Líbano', 'codigo_movil'=>'961'],
            ['nombre'=>'Lesoto', 'codigo_movil'=>'266'],
            ['nombre'=>'Liberia', 'codigo_movil'=>'231'],
            ['nombre'=>'Libia', 'codigo_movil'=>'218'],
            ['nombre'=>'Liechtenstein', 'codigo_movil'=>'423'],
            ['nombre'=>'Lituania', 'codigo_movil'=>'370'],
            ['nombre'=>'Luxemburgo', 'codigo_movil'=>'352'],
            ['nombre'=>'Macau', 'codigo_movil'=>'853'],
            ['nombre'=>'Macedonia', 'codigo_movil'=>'389'],
            ['nombre'=>'Madagascar', 'codigo_movil'=>'261'],
            ['nombre'=>'Malaui', 'codigo_movil'=>'265'],
            ['nombre'=>'Malasia', 'codigo_movil'=>'60'],
            ['nombre'=>'Maldivas', 'codigo_movil'=>'960'],
            ['nombre'=>'Malí', 'codigo_movil'=>'223'],
            ['nombre'=>'Malta', 'codigo_movil'=>'356'],
            ['nombre'=>'Islas Marshall', 'codigo_movil'=>'692'],
            ['nombre'=>'Martinica', 'codigo_movil'=>'596'],
            ['nombre'=>'Mauritania', 'codigo_movil'=>'222'],
            ['nombre'=>'Islas Mauricio', 'codigo_movil'=>'230'],
            ['nombre'=>'México', 'codigo_movil'=>'52'],
            ['nombre'=>'Micronesia', 'codigo_movil'=>'691'],
            ['nombre'=>'Moldova', 'codigo_movil'=>'373'],
            ['nombre'=>'Mónaco', 'codigo_movil'=>'377'],
            ['nombre'=>'Mongolia', 'codigo_movil'=>'976'],
            ['nombre'=>'Montenegro', 'codigo_movil'=>'382'],
            ['nombre'=>'Montserrat', 'codigo_movil'=>'1 (664)'],
            ['nombre'=>'Marruecos', 'codigo_movil'=>'212'],
            ['nombre'=>'Mozambique', 'codigo_movil'=>'258'],
            ['nombre'=>'Myanmar (Birmania)', 'codigo_movil'=>'95'],
            ['nombre'=>'Namibia', 'codigo_movil'=>'264'],
            ['nombre'=>'Nauru', 'codigo_movil'=>'674'],
            ['nombre'=>'Nepal', 'codigo_movil'=>'977'],
            ['nombre'=>'Holanda', 'codigo_movil'=>'31'],
            ['nombre'=>'Antillas Neerlandesas (Bonaire, Curacao, Saba, S Eustis)', 'codigo_movil'=>'599'],
            ['nombre'=>'Nueva Caledonia', 'codigo_movil'=>'687'],
            ['nombre'=>'Nueva Zelanda', 'codigo_movil'=>'64'],
            ['nombre'=>'Nicaragua', 'codigo_movil'=>'505'],
            ['nombre'=>'Níger', 'codigo_movil'=>'227'],
            ['nombre'=>'Nigeria', 'codigo_movil'=>'234'],
            ['nombre'=>'Islas Marianas del Norte', 'codigo_movil'=>'1 (670)'],
            ['nombre'=>'Noruega', 'codigo_movil'=>'47'],
            ['nombre'=>'Omán', 'codigo_movil'=>'968'],
            ['nombre'=>'Pakistán', 'codigo_movil'=>'92'],
            ['nombre'=>'Palaos', 'codigo_movil'=>'680'],
            ['nombre'=>'Autoridad Palestina', 'codigo_movil'=>'970'],
            ['nombre'=>'Panamá', 'codigo_movil'=>'507'],
            ['nombre'=>'Papúa Nueva Guinea', 'codigo_movil'=>'675'],
            ['nombre'=>'Paraguay', 'codigo_movil'=>'595'],
            ['nombre'=>'Perú', 'codigo_movil'=>'51'],
            ['nombre'=>'Filipinas', 'codigo_movil'=>'63'],
            ['nombre'=>'Polonia', 'codigo_movil'=>'48'],
            ['nombre'=>'Portugal', 'codigo_movil'=>'351'],
            ['nombre'=>'Qatar', 'codigo_movil'=>'974'],
            ['nombre'=>'Reunión', 'codigo_movil'=>'262'],
            ['nombre'=>'Rumania', 'codigo_movil'=>'40'],
            ['nombre'=>'Rusia', 'codigo_movil'=>'7'],
            ['nombre'=>'Ruanda', 'codigo_movil'=>'250'],
            ['nombre'=>'Saipán (Islas Marianas del Norte)', 'codigo_movil'=>'1 (670)'],
            ['nombre'=>'Samoa', 'codigo_movil'=>'685'],
            ['nombre'=>'San Marino', 'codigo_movil'=>'378'],
            ['nombre'=>'Santo Tomé/Príncipe', 'codigo_movil'=>'239'],
            ['nombre'=>'Arabia Saudita', 'codigo_movil'=>'966'],
            ['nombre'=>'Senegal', 'codigo_movil'=>'221'],
            ['nombre'=>'Serbia', 'codigo_movil'=>'381'],
            ['nombre'=>'Seychelles', 'codigo_movil'=>'248'],
            ['nombre'=>'Sierra Leona', 'codigo_movil'=>'232'],
            ['nombre'=>'Singapur', 'codigo_movil'=>'65'],
            ['nombre'=>'Isla de San Martín', 'codigo_movil'=>'1 (721)'],
            ['nombre'=>'Eslovaquia', 'codigo_movil'=>'421'],
            ['nombre'=>'Eslovenia', 'codigo_movil'=>'386'],
            ['nombre'=>'Islas Salomón', 'codigo_movil'=>'677'],
            ['nombre'=>'Sudáfrica', 'codigo_movil'=>'27'],
            ['nombre'=>'Sudán Meridional', 'codigo_movil'=>'211'],
            ['nombre'=>'España', 'codigo_movil'=>'34'],
            ['nombre'=>'Sri Lanka', 'codigo_movil'=>'94'],
            ['nombre'=>'San Pedro/Miquelón', 'codigo_movil'=>'508'],
            ['nombre'=>'San Cristóbal/Nieves', 'codigo_movil'=>'1 (869)'],
            ['nombre'=>'Santa Lucía', 'codigo_movil'=>'1 (758)'],
            ['nombre'=>'San Vicente/Granadinas', 'codigo_movil'=>'1 (784)'],
            ['nombre'=>'Sudán', 'codigo_movil'=>'249'],
            ['nombre'=>'Suriname', 'codigo_movil'=>'597'],
            ['nombre'=>'Suazilandia', 'codigo_movil'=>'268'],
            ['nombre'=>'Suecia', 'codigo_movil'=>'46'],
            ['nombre'=>'Suiza', 'codigo_movil'=>'41'],
            ['nombre'=>'Siria', 'codigo_movil'=>'963'],
            ['nombre'=>'Taiwán', 'codigo_movil'=>'886'],
            ['nombre'=>'Tayikistán', 'codigo_movil'=>'992'],
            ['nombre'=>'Tanzania', 'codigo_movil'=>'255'],
            ['nombre'=>'Tailandia', 'codigo_movil'=>'66'],
            ['nombre'=>'Togo', 'codigo_movil'=>'228'],
            ['nombre'=>'Tokelau', 'codigo_movil'=>'690'],
            ['nombre'=>'Tonga', 'codigo_movil'=>'676'],
            ['nombre'=>'Trinidad y Tobago', 'codigo_movil'=>'1 (868)'],
            ['nombre'=>'Túnez', 'codigo_movil'=>'216'],
            ['nombre'=>'Turquía', 'codigo_movil'=>'90'],
            ['nombre'=>'Turkmenistán', 'codigo_movil'=>'993'],
            ['nombre'=>'Islas Turcas y Caicos', 'codigo_movil'=>'1 (649)'],
            ['nombre'=>'Tuvalu', 'codigo_movil'=>'688'],
            ['nombre'=>'Uganda', 'codigo_movil'=>'256'],
            ['nombre'=>'Ucrania', 'codigo_movil'=>'380'],
            ['nombre'=>'Emiratos Árabes Unidos', 'codigo_movil'=>'971'],
            ['nombre'=>'Reino Unido', 'codigo_movil'=>'44'],
            ['nombre'=>'Uruguay', 'codigo_movil'=>'598'],
            ['nombre'=>'Uzbekistán', 'codigo_movil'=>'998'],
            ['nombre'=>'Vanuatu', 'codigo_movil'=>'678'],
            ['nombre'=>'Venezuela', 'codigo_movil'=>'58'],
            ['nombre'=>'Vietnam', 'codigo_movil'=>'84'],
            ['nombre'=>'Yemen', 'codigo_movil'=>'967'],
            ['nombre'=>'Zambia', 'codigo_movil'=>'260'],
            ['nombre'=>'Zimbabue', 'codigo_movil'=>'263'],
        ];
        foreach ($paises as $key => $value) {
            Pais::create($value);
        }
    }
}
